// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKC9saux_QhVQigwuyV1YrAAZh_UqL-HI',
    appId: '1:185566016237:android:d3886278a36d970f22d2e4',
    messagingSenderId: '185566016237',
    projectId: 'myfinalproject-15fed',
    storageBucket: 'myfinalproject-15fed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMTh9djjN9VSDWubpTicIt15xhm9q7gtA',
    appId: '1:185566016237:ios:1485e5086cfe5cc722d2e4',
    messagingSenderId: '185566016237',
    projectId: 'myfinalproject-15fed',
    storageBucket: 'myfinalproject-15fed.appspot.com',
    iosClientId: '185566016237-ahpm5s5bbse5ff0p9gbh4i1d14eso7jb.apps.googleusercontent.com',
    iosBundleId: 'com.example.mdc100Series',
  );
}
